version: '3.8'

services:
  affiliate-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: affiliate-web
    environment:
      - NODE_ENV=production
    restart: unless-stopped
#    healthcheck:
#      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 40s
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.affiliate-web.rule=Host(`affiliate-web.acsdev.review`)"
      - "traefik.http.routers.affiliate-web.entrypoints=websecure"
      - "traefik.http.routers.affiliate-web.tls=true"
      - "traefik.http.routers.affiliate-web.tls.certresolver=letsencrypt"
      - "traefik.http.services.affiliate-web.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.affiliate-web.middlewares=redirect-to-https"

networks:
  proxy:
    external: true
